import { cp, mkdir, rm } from "node:fs/promises";
const name = process.argv[2];
if (name !== "core" && name !== "train") throw new Error("Expected core or train.");
const root = new URL("../", import.meta.url);
const output = new URL(`packages/${name}/docs/`, root);
await rm(new URL(`packages/${name}/dist/`, root), { recursive: true, force: true });
await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
await cp(new URL("docs/", root), output, { recursive: true });
await cp(new URL("skills/matchbox/SKILL.md", root), new URL("agent-skill.md", output));
